### ISSUE TITLE
Document build and publish steps

### ISSUE THREAD

**Issue by gadams999** [awslabs/aws-greengrass-labs-modbus-tcp-protocol-adapter#1]
Hi,

In order for new visitors to successfully utilize this component, it would helpful to have full build and publish steps provided. Right now the main README describes the configuration of the component. Ask is to please document _how_ to build, then publish, the component, preferably using the [gdk](https://github.com/aws-greengrass/aws-greengrass-gdk-cli).

**Comment by avipinku** [comment]
Hi Gavin,

This is actively being worked on and we will update this issue once completed. Thanks for bringing this up!

**Comment by SunithaE** [comment]
+1

**Comment by SunithaE** [comment]
> Hi,
> 
> In order for new visitors to successfully utilize this component, it would helpful to have full build and publish steps provided. Right now the main README describes the configuration of the component. Ask is to please document _how_ to build, then publish, the component, preferably using the [gdk](https://github.com/aws-greengrass/aws-greengrass-gdk-cli).


+1

**Comment by Yukinobu-Mine** [comment]
@gadams999 @avipinku  I created pull request #2 .
Please review and approve if looking good.
